version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

networks:
  app-network:
    driver: bridge

volumes:
  db-data: