CREATE TABLE T_CODES (
    INVITE_CODE VARCHAR(255) NOT NULL,
    AUTHOR_EMAIL VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(255),
    IS_USED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    USED_AT TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (INVITE_CODE)
);